---
- alias: Gunnig Rho
  description: male dwarf fighter
- alias: Sis. Delilah
  description: female human cleric
- alias: Melen Quickstab
  description: male halfling rogue
- alias: Disenion Solferalis
  description: female elf wizard
